import { test, expect } from '@playwright/test';

test('focused training keeps real inputs, timers and navigation reachable on narrow phones', async ({ page }, info) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Hallo, Jona' })).toBeVisible();
  await page.screenshot({ path: `test-results/previews/design-start-${info.project.name}.png` });
  await page.getByRole('button', { name: 'Training ansehen & starten' }).click();
  await page.getByRole('button', { name: /^Training beginnen/ }).click();
  await expect(page.locator('.bottom-nav')).toBeHidden();
  await expect(page.locator('.workout-dock')).toBeVisible();
  const reps = page.getByLabel('Satz 1 Wiederholungen', { exact: true });
  await expect(reps).toHaveValue('');
  await expect(reps).toHaveAttribute('placeholder', '–');
  await expect(page.locator('.set-target').first()).toHaveText('4–7');
  await expect(page.getByLabel('Verfügbarer Gewichtsschritt (Zusatz-kg)')).toBeHidden();
  await page.locator('.exercise-thumbnail img').evaluateAll(images => Promise.all(images.map(img => img.decode())));
  await page.screenshot({ path: `test-results/previews/design-training-${info.project.name}.png` });
  await reps.fill('7');
  await expect(page.locator('.workout-dock')).toBeVisible();
  await page.getByLabel('Satz 1 Gewicht', { exact: true }).fill('5');
  await page.getByRole('button', { name: 'Satz 1 speichern', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Satz 1 wieder öffnen', exact: true })).toBeVisible();
  await expect(page.locator('.workout-dock')).toBeVisible();
  await expect(page.locator('.workout-dock').getByText('Satzpause', { exact: true })).toBeVisible();
  await expect(page.locator('.set-table-row-current').getByRole('button')).toHaveAccessibleName('Satz 2 speichern');
  await page.screenshot({ path: `test-results/previews/design-timer-${info.project.name}.png` });
  await page.getByRole('button', { name: '‹ Übersicht', exact: true }).click();
  await expect(page.locator('.bottom-nav')).toBeVisible();
  await expect(page.locator('.workout-dock')).toHaveCount(0);
  await page.getByRole('button', { name: /^Bulgarian Split Squat mit Kurzhanteln/ }).click();
  await page.setViewportSize({ width: 320, height: 680 });
  await expect(page.getByLabel('Satz 1 Wiederholungen links', { exact: true })).toBeVisible();
  const bounds = await page.locator('.set-table-row-current input').evaluateAll(inputs => inputs.map(input => ({ width: input.getBoundingClientRect().width, height: input.getBoundingClientRect().height })));
  expect(bounds.every(b => b.width >= 40 && b.height >= 44)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('.exercise-thumbnail img').evaluateAll(images => Promise.all(images.map(img => img.decode())));
  await page.screenshot({ path: `test-results/previews/design-320-${info.project.name}.png` });
  await page.getByRole('button', { name: 'Pausieren', exact: true }).click();
  await expect(page.locator('.bottom-nav')).toBeVisible();
  const stored = await page.evaluate(async () => (await (await import('/src/db.js')).getActiveSession()).entries['mo-pullup'].sets);
  expect(stored).toHaveLength(1);
  expect(stored[0].reps).toBe(7);
  expect(stored[0].weightKg).toBe(5);
});
