"""Publish only explicitly accepted and assembled exercise illustrations."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
jobs = json.loads((root / 'assets/motion/production-jobs.json').read_text())
exercises = json.loads((root / 'assets/motion/exercises-for-production.json').read_text())
by_id = {ex['id']: ex for ex in exercises}
catalog = {}
for job in jobs:
    if job['status'] != 'accepted':
        continue
    for id in job['ids']:
        ex = by_id[id]
        paths = [root / f'assets/motion/{job["key"]}/{n+1}.png' for n in range(len(job['labels']))]
        assert all(p.is_file() for p in paths), id
        cues = [s.strip().rstrip('.') + '.' for s in ((ex.get('video') or {}).get('cues') or ex.get('note') or '').split(';') if s.strip()]
        if ex.get('perSide'):
            cues.append('Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite.')
        if job.get('exampleNote'):
            cues.insert(0, job['exampleNote'])
        sequence = job.get('sequence', list(range(4)) if len(job['labels']) == 4 else [0, 1, 2, 1])
        catalog[id] = dict(directory=job['key'], file='loop.gif', labels=job['labels'],
            sequence=sequence,
            durations=job.get('durations', [1100] * len(sequence)),
            cues=cues, description=ex['name'] + ': schematische Bewegungsphasen.')
(root / 'src/motionCatalog.js').write_text('// Generated by scripts/build-motion-catalog.py. Only accepted assets.\nexport const GENERATED_MOTIONS = ' + json.dumps(catalog, ensure_ascii=False, indent=2) + ';\n')
legacy = {'mo-rdl~db', 'mo-gobletsquat', 'mo-calf'}
coverage = [{'id': ex['id'], 'name': ex['name'], 'animation': ex['id'] in catalog or ex['id'] in legacy} for ex in exercises]
(root / 'assets/motion/COVERAGE.json').write_text(json.dumps(coverage, ensure_ascii=False, indent=2) + '\n')
print(f'{sum(x["animation"] for x in coverage)}/{len(coverage)} exercise identities have animations')
