// Generated by scripts/build-motion-catalog.py. Only accepted assets.
export const GENERATED_MOTIONS = {
  "mo-dip": {
    "directory": "ring-dip",
    "file": "loop.gif",
    "labels": [
      "Stützposition",
      "Kontrolliert absenken",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Ringe stabil.",
      "kontrolliert absenken.",
      "kein Fallen in die Schulter.",
      "kraftvoll hoch."
    ],
    "description": "Weighted Ring Dip, kontrolliert tief: schematische Bewegungsphasen."
  },
  "do-bench~db": {
    "directory": "bench-db-v3",
    "file": "loop.gif",
    "labels": [
      "Oben stabilisieren",
      "Kontrolliert absenken",
      "Hanteln neben der Brust"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Schulterblätter stabil.",
      "Handgelenke über Unterarmen.",
      "kontrolliert absenken."
    ],
    "description": "Kurzhantel-Bankdrücken: schematische Bewegungsphasen."
  },
  "mo-dip~bench-db": {
    "directory": "bench-db-v3",
    "file": "loop.gif",
    "labels": [
      "Oben stabilisieren",
      "Kontrolliert absenken",
      "Hanteln neben der Brust"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Schulterblätter stabil.",
      "Handgelenke über Unterarmen.",
      "kontrolliert absenken."
    ],
    "description": "Kurzhantel-Bankdrücken: schematische Bewegungsphasen."
  },
  "sa-ringpushup~bench-db": {
    "directory": "bench-db-v3",
    "file": "loop.gif",
    "labels": [
      "Oben stabilisieren",
      "Kontrolliert absenken",
      "Hanteln neben der Brust"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Schulterblätter stabil.",
      "Handgelenke über Unterarmen.",
      "kontrolliert absenken."
    ],
    "description": "Kurzhantel-Bankdrücken: schematische Bewegungsphasen."
  },
  "mo-splitsquat": {
    "directory": "bulgarian",
    "file": "loop.gif",
    "labels": [
      "Stabiler Stand",
      "Absenken",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Vorderer Fuss voll belastet.",
      "kontrolliert tief.",
      "kein Aufprall unten.",
      "Becken stabil.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Deep Bulgarian Split Squat KH: schematische Bewegungsphasen."
  },
  "do-pistol~bulgarian": {
    "directory": "bulgarian",
    "file": "loop.gif",
    "labels": [
      "Stabiler Stand",
      "Absenken",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Vorderer Fuss voll belastet.",
      "kontrolliert tief.",
      "kein Aufprall unten.",
      "Becken stabil.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Bulgarian Split Squat mit Kurzhanteln: schematische Bewegungsphasen."
  },
  "mo-splitsquat~stepup": {
    "directory": "stepup-db",
    "file": "loop.gif",
    "labels": [
      "Ganzer Fuß auf der Auflage",
      "Mit dem oberen Bein hochdrücken",
      "Oben stabilisieren"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Den ganzen oberen Fuß aufsetzen.",
      "mit dem oberen Bein hochdrücken.",
      "kontrolliert zum Boden zurückkehren.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Step-up mit Kurzhanteln: schematische Bewegungsphasen."
  },
  "do-pistol~stepup": {
    "directory": "stepup-db",
    "file": "loop.gif",
    "labels": [
      "Ganzer Fuß auf der Auflage",
      "Mit dem oberen Bein hochdrücken",
      "Oben stabilisieren"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Den ganzen oberen Fuß aufsetzen.",
      "mit dem oberen Bein hochdrücken.",
      "kontrolliert zum Boden zurückkehren.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Step-up mit Kurzhanteln: schematische Bewegungsphasen."
  },
  "mo-rdl~rdl-guided": {
    "directory": "rdl-guided",
    "file": "loop.gif",
    "labels": [
      "Aufrecht stehen",
      "Hüfte zurück",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Beispiel an einer geführten Hantelstange. Griff und Stand an die vorhandene Station anpassen.",
      "Hüfte nach hinten.",
      "leichte Kniebeugung.",
      "Gewicht körpernah.",
      "Spannung in Hamstrings."
    ],
    "description": "RDL an vorhandener geführter Station: schematische Bewegungsphasen."
  },
  "mo-nordic": {
    "directory": "nordic",
    "file": "loop.gif",
    "labels": [
      "Kniestand mit fixierten Knöcheln",
      "Als Einheit nach vorn neigen",
      "Mit den Händen abfangen"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Gerade Linie Schulter-Hüfte-Knie.",
      "Bewegung nur aus den Hamstrings.",
      "kontrolliert bis zur Grenze, dann mit den Armen abfangen."
    ],
    "description": "Nordic Hamstring Curl: schematische Bewegungsphasen."
  },
  "do-nordic": {
    "directory": "nordic",
    "file": "loop.gif",
    "labels": [
      "Kniestand mit fixierten Knöcheln",
      "Als Einheit nach vorn neigen",
      "Mit den Händen abfangen"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Gerade Linie Schulter-Hüfte-Knie.",
      "Bewegung nur aus den Hamstrings.",
      "kontrolliert bis zur Grenze, dann mit den Armen abfangen."
    ],
    "description": "Nordic Hamstring Curl: schematische Bewegungsphasen."
  },
  "mo-extrot": {
    "directory": "external-rotation",
    "file": "loop.gif",
    "labels": [
      "Unterarm vor dem Bauch",
      "Nach außen drehen",
      "Oberarm bleibt ruhig"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Ellbogen ca. 90 Grad.",
      "Oberarm ruhig.",
      "nur Schulter rotiert.",
      "Rückweg kontrolliert."
    ],
    "description": "Cable External Rotation: schematische Bewegungsphasen."
  },
  "mo-neck": {
    "directory": "neck-isometric",
    "file": "loop.gif",
    "labels": [
      "Stirn · Kopf still halten",
      "Hinterkopf · Kopf still halten",
      "Rechte Seite · Kopf still halten",
      "Linke Seite · Kopf still halten"
    ],
    "sequence": [
      0,
      1,
      2,
      3
    ],
    "durations": [
      2500,
      2500,
      2500,
      2500
    ],
    "cues": [
      "Vier getrennte Halterichtungen. Der Kopf bleibt neutral und bewegt sich beim Druck gegen die Hand nicht.",
      "Kopf bleibt still.",
      "Kraft gleichmässig aufbauen.",
      "Nacken neutral, kein Ausweichen."
    ],
    "description": "Nacken-Isometrie 4-Wege: schematische Bewegungsphasen."
  },
  "do-neck": {
    "directory": "neck-isometric",
    "file": "loop.gif",
    "labels": [
      "Stirn · Kopf still halten",
      "Hinterkopf · Kopf still halten",
      "Rechte Seite · Kopf still halten",
      "Linke Seite · Kopf still halten"
    ],
    "sequence": [
      0,
      1,
      2,
      3
    ],
    "durations": [
      2500,
      2500,
      2500,
      2500
    ],
    "cues": [
      "Vier getrennte Halterichtungen. Der Kopf bleibt neutral und bewegt sich beim Druck gegen die Hand nicht.",
      "Kopf bleibt still.",
      "Kraft gleichmässig aufbauen.",
      "Nacken neutral, kein Ausweichen."
    ],
    "description": "Nacken-Isometrie 4-Wege: schematische Bewegungsphasen."
  },
  "sa-neck": {
    "directory": "neck-isometric",
    "file": "loop.gif",
    "labels": [
      "Stirn · Kopf still halten",
      "Hinterkopf · Kopf still halten",
      "Rechte Seite · Kopf still halten",
      "Linke Seite · Kopf still halten"
    ],
    "sequence": [
      0,
      1,
      2,
      3
    ],
    "durations": [
      2500,
      2500,
      2500,
      2500
    ],
    "cues": [
      "Vier getrennte Halterichtungen. Der Kopf bleibt neutral und bewegt sich beim Druck gegen die Hand nicht.",
      "Kopf bleibt still.",
      "Kraft gleichmässig aufbauen.",
      "Nacken neutral, kein Ausweichen."
    ],
    "description": "Nacken-Isometrie 4-Wege: schematische Bewegungsphasen."
  },
  "di-cardio": {
    "directory": "easy-run",
    "file": "loop.gif",
    "labels": [
      "Lockerer Laufschritt",
      "Ruhig weiterlaufen",
      "Gleichmäßiger Rhythmus"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1100,
      1100,
      1100
    ],
    "cues": [
      "Beispiel: lockeres Joggen. Du kannst deine gewohnte Ausdauerform nutzen; die Bildfolge zeigt keinen vollständigen Laufzyklus.",
      "Nicht dem Tempo hinterherlaufen.",
      "Herzfrequenz und lockeres Gefühl steuern."
    ],
    "description": "Aerobic mit Polar-Gurt: schematische Bewegungsphasen."
  },
  "mi-cardio": {
    "directory": "easy-run",
    "file": "loop.gif",
    "labels": [
      "Lockerer Laufschritt",
      "Ruhig weiterlaufen",
      "Gleichmäßiger Rhythmus"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1100,
      1100,
      1100
    ],
    "cues": [
      "Beispiel: lockeres Joggen. Du kannst deine gewohnte Ausdauerform nutzen; die Bildfolge zeigt keinen vollständigen Laufzyklus.",
      "Nicht dem Tempo hinterherlaufen.",
      "Herzfrequenz und lockeres Gefühl steuern."
    ],
    "description": "Kurze lockere Ausdauer: schematische Bewegungsphasen."
  },
  "di-aslr": {
    "directory": "aslr",
    "file": "loop.gif",
    "labels": [
      "Rückenlage",
      "Bein aktiv anheben",
      "Becken und Gegenbein ruhig"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Knie gestreckt.",
      "Gegenbein ruhig.",
      "aktiv hoch, kontrolliert runter.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Active Straight-Leg Raise: schematische Bewegungsphasen."
  },
  "di-hipflexor": {
    "directory": "hip-flexor-hold",
    "file": "loop.gif",
    "labels": [
      "Halbkniestand",
      "Becken ausrichten",
      "Position ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1300,
      3500
    ],
    "cues": [
      "Gesäss an.",
      "Rippen unten.",
      "Becken leicht posterior.",
      "Stretch vorne an der Hüfte.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Half-kneeling Hip Flexor Hold: schematische Bewegungsphasen."
  },
  "di-frontsplit": {
    "directory": "front-split",
    "file": "loop.gif",
    "labels": [
      "Mit Blöcken abstützen",
      "Kontrolliert in die Position",
      "Ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1300,
      3500
    ],
    "cues": [
      "Hüften möglichst quadratisch.",
      "nicht federn.",
      "Tiefe nur kontrolliert steigern.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Front Split mit Blocks/Stütze: schematische Bewegungsphasen."
  },
  "di-atg": {
    "directory": "long-split-squat",
    "file": "loop.gif",
    "labels": [
      "Langer Schrittstand",
      "Langsam absenken",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Leicht.",
      "langsam tief.",
      "hinteres Bein/Hüftbeuger lang.",
      "keine Schmerz-ROM.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "ATG/Long Split Squat, leicht: schematische Bewegungsphasen."
  },
  "di-rdl-light": {
    "directory": "light-hamstring-hinge",
    "file": "loop.gif",
    "labels": [
      "Weiche Knie",
      "Hüfte nach hinten",
      "Kontrollierte Dehnung"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Rücken kontrolliert.",
      "Hüfte zurück.",
      "nur so tief wie Becken/Wirbelsäule sauber bleiben."
    ],
    "description": "Straight-leg RDL / Hamstring hinge, leicht: schematische Bewegungsphasen."
  },
  "do-lsit": {
    "directory": "tuck-lsit",
    "file": "loop.gif",
    "labels": [
      "Stütz vorbereiten",
      "Hüfte anheben",
      "Tuck-Position halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1300,
      3500
    ],
    "cues": [
      "Boden/Barren wegdrücken.",
      "Hüfte aktiv beugen.",
      "kein passives Hängen."
    ],
    "description": "L-Sit / Tuck L-Sit: schematische Bewegungsphasen."
  },
  "do-handstand": {
    "directory": "handstand-wall",
    "file": "loop.gif",
    "labels": [
      "An der Wand ausrichten",
      "Boden aktiv wegdrücken",
      "Balance ruhig kontrollieren"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1600,
      1800,
      3000
    ],
    "cues": [
      "Gezeigt wird eine Wand-Variante als Erinnerung an die Halteposition. Einstieg und Abgang im Technikvideo ansehen.",
      "Boden aktiv wegdrücken.",
      "Rippen/Becken kontrollieren.",
      "Finger für Balance nutzen."
    ],
    "description": "Handstand: schematische Bewegungsphasen."
  },
  "do-bench~bench-guided": {
    "directory": "bench-guided",
    "file": "loop.gif",
    "labels": [
      "Oben stabilisieren",
      "Geführt absenken",
      "Kontrollierte untere Position"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Beispiel an einer geführten Stange. Griff, Bankposition und Bewegungsbahn müssen zu deiner vorhandenen Station passen.",
      "Schulterblätter stabil.",
      "Handgelenke über Unterarmen.",
      "kontrolliert absenken."
    ],
    "description": "Geführtes Bankdrücken: schematische Bewegungsphasen."
  },
  "sa-ringpushup": {
    "directory": "ring-pushup",
    "file": "loop.gif",
    "labels": [
      "Stabiler Stütz",
      "Körper als Einheit absenken",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Körper als Brett.",
      "Ringe kontrolliert.",
      "tiefe schmerzfreie ROM."
    ],
    "description": "Deep Ring Push-up: schematische Bewegungsphasen."
  },
  "do-bench~ring-pushup": {
    "directory": "ring-pushup",
    "file": "loop.gif",
    "labels": [
      "Stabiler Stütz",
      "Körper als Einheit absenken",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Körper als Brett.",
      "Ringe kontrolliert.",
      "tiefe schmerzfreie ROM."
    ],
    "description": "Ringliegestütz: schematische Bewegungsphasen."
  },
  "do-ringrow": {
    "directory": "ring-row-v2",
    "file": "loop.gif",
    "labels": [
      "Gerade Körperlinie",
      "Brust zu den Ringen ziehen",
      "Schulterblätter kontrollieren"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Kein Hüftknick.",
      "Brust zu den Ringen.",
      "Scapula kontrolliert."
    ],
    "description": "Ring Row mit maximal sauberem ROM: schematische Bewegungsphasen."
  },
  "sa-cablerow~ring-row": {
    "directory": "ring-row-v2",
    "file": "loop.gif",
    "labels": [
      "Gerade Körperlinie",
      "Brust zu den Ringen ziehen",
      "Schulterblätter kontrollieren"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Kein Hüftknick.",
      "Brust zu den Ringen.",
      "Scapula kontrolliert."
    ],
    "description": "Ringrudern: schematische Bewegungsphasen."
  },
  "sa-cablerow": {
    "directory": "cable-row",
    "file": "loop.gif",
    "labels": [
      "Arme lang",
      "Ellbogen nach hinten",
      "Griff zu den unteren Rippen"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Rumpf ruhig.",
      "Ellbogen ziehen.",
      "kontrollierte Pro-/Retraktion."
    ],
    "description": "Cable Row: schematische Bewegungsphasen."
  },
  "do-ringrow~cable-row": {
    "directory": "cable-row",
    "file": "loop.gif",
    "labels": [
      "Arme lang",
      "Ellbogen nach hinten",
      "Griff zu den unteren Rippen"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Rumpf ruhig.",
      "Ellbogen ziehen.",
      "kontrollierte Pro-/Retraktion."
    ],
    "description": "Kabelrudern: schematische Bewegungsphasen."
  },
  "do-ohp": {
    "directory": "db-overhead-press",
    "file": "loop.gif",
    "labels": [
      "Hanteln auf Schulterhöhe",
      "Nach oben drücken",
      "Über den Schultern stabilisieren"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Rippen unten.",
      "Kern angespannt.",
      "Kurzhanteln enden über den Schultern.",
      "kontrolliert absenken."
    ],
    "description": "KH Schulterdrücken, kontrolliert: schematische Bewegungsphasen."
  },
  "do-hipthrust": {
    "directory": "hip-thrust",
    "file": "loop.gif",
    "labels": [
      "Schulterblätter auf der Bank",
      "Hüfte anheben",
      "Oben Gesäß anspannen"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Die Animation zeigt die Grundbewegung ohne Zusatzgewicht.",
      "Becken hoch durch Gesäss.",
      "Schienbein oben etwa senkrecht.",
      "kein Hohlkreuz-Lockout."
    ],
    "description": "Hip Thrust: schematische Bewegungsphasen."
  },
  "do-revnordic": {
    "directory": "reverse-nordic",
    "file": "loop.gif",
    "labels": [
      "Aufrechter Kniestand",
      "Als Einheit zurücklehnen",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Gesäss/Bauch an.",
      "kontrolliert zurück.",
      "ROM progressiv."
    ],
    "description": "Reverse Nordic: schematische Bewegungsphasen."
  },
  "do-scappullup": {
    "directory": "scapular-pullup",
    "file": "loop.gif",
    "labels": [
      "Langer Hang",
      "Schulterblätter aktiv bewegen",
      "Aktiven Hang halten"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Aus Hang aktiv depressieren.",
      "kurze Kontrolle.",
      "langsam zurück."
    ],
    "description": "Scapular Pull-up: schematische Bewegungsphasen."
  },
  "do-wallshoulder": {
    "directory": "wall-shoulder-liftoff",
    "file": "loop.gif",
    "labels": [
      "Arme lang an der Wand",
      "Hände aktiv lösen",
      "Rumpf ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Rippen unten.",
      "Ellbogen lang.",
      "aktive Schulterflexion."
    ],
    "description": "Wall Shoulder Flexion Lift-off: schematische Bewegungsphasen."
  },
  "do-pikelift": {
    "directory": "seated-compression",
    "file": "loop.gif",
    "labels": [
      "Sitz mit langen Beinen",
      "Fersen aktiv anheben",
      "Kleine Höhe kontrollieren"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Knie lang.",
      "Oberschenkel aktiv.",
      "kleine saubere Lift-offs reichen."
    ],
    "description": "Seated Pike/Straddle Compression Lift: schematische Bewegungsphasen."
  },
  "do-straddlegm": {
    "directory": "straddle-goodmorning",
    "file": "loop.gif",
    "labels": [
      "Aufrechter Grätschsitz",
      "Aus der Hüfte vorlehnen",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Hip hinge.",
      "leicht.",
      "Adduktoren/Hamstrings unter kontrollierter Last."
    ],
    "description": "Straddle Good Morning, leicht: schematische Bewegungsphasen."
  },
  "do-pancake": {
    "directory": "pancake-hold",
    "file": "loop.gif",
    "labels": [
      "Grätschsitz",
      "Langsam vorlehnen",
      "Ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1500,
      3500
    ],
    "cues": [
      "Straddle stabil.",
      "ruhig atmen.",
      "kontrollierte Endposition."
    ],
    "description": "Pancake Hold: schematische Bewegungsphasen."
  },
  "do-latstretch": {
    "directory": "ring-lat-stretch",
    "file": "loop.gif",
    "labels": [
      "Ringe sicher greifen",
      "Hüfte zurückführen",
      "Dehnung ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1500,
      3500
    ],
    "cues": [
      "Ruhige Atmung.",
      "Schulter tolerierbar.",
      "kein Schmerz vorne im Gelenk."
    ],
    "description": "Lat/Overhead Stretch an Ringen: schematische Bewegungsphasen."
  },
  "mi-shouldercars": {
    "directory": "shoulder-cars",
    "file": "loop.gif",
    "labels": [
      "Arm nach vorn führen",
      "Über Kopf bewegen",
      "Kontrolliert nach hinten führen",
      "Kreis schließen"
    ],
    "sequence": [
      0,
      1,
      2,
      3
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Ganzkörperspannung.",
      "Schulterkreis aktiv.",
      "keine Schwungbewegung.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Controlled Articular Rotations: Schulter: schematische Bewegungsphasen."
  },
  "mi-9090": {
    "directory": "hip-9090",
    "file": "loop.gif",
    "labels": [
      "90/90-Sitz",
      "Kontrolliert wechseln",
      "Andere Seite",
      "Kleiner aktiver Lift-off"
    ],
    "sequence": [
      0,
      1,
      2,
      3
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Becken kontrollieren.",
      "Lift-off aktiv aus Hüftrotation.",
      "ROM nicht erzwingen.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "90/90 Hip Switch + Lift-off: schematische Bewegungsphasen."
  },
  "mi-thoracic": {
    "directory": "thoracic-rotation",
    "file": "loop.gif",
    "labels": [
      "Vierfüßler stabilisieren",
      "Brustwirbelsäule drehen",
      "Becken ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Becken ruhig.",
      "Rotation statt Seitneigung.",
      "langsam.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Thoracic Rotation im Vierfüssler: schematische Bewegungsphasen."
  },
  "mi-wrist": {
    "directory": "wrist-rocks",
    "file": "loop.gif",
    "labels": [
      "Hände flach aufsetzen",
      "Gewicht nach vorn verlagern",
      "Kontrolliert zurück"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Keine scharfen Schmerzen.",
      "Druck langsam steigern.",
      "Ellbogen kontrolliert."
    ],
    "description": "Wrist Rocks: schematische Bewegungsphasen."
  },
  "mi-hang": {
    "directory": "towel-hang",
    "file": "loop.gif",
    "labels": [
      "Am Handtuch hängen",
      "Schultern aktivieren",
      "Arme bleiben lang"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Arme lang.",
      "Scapula bewegt.",
      "Rumpf ruhig.",
      "Griff aktiv zudrücken, nicht nur halten."
    ],
    "description": "Passive Hang -> Active Hang (Handtuch-Griff): schematische Bewegungsphasen."
  },
  "mi-cossack": {
    "directory": "cossack",
    "file": "loop.gif",
    "labels": [
      "Breiter Stand",
      "Gewicht zu einer Seite",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Belasteter Fuss voll am Boden.",
      "Knie folgt Zehen.",
      "langes Bein kontrolliert.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Cossack Squat Flow: schematische Bewegungsphasen."
  },
  "fr-cossack": {
    "directory": "cossack",
    "file": "loop.gif",
    "labels": [
      "Breiter Stand",
      "Gewicht zu einer Seite",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Belasteter Fuss stabil.",
      "Knie folgt Zehen.",
      "aktiv aus der Tiefe.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Cossack Squat: schematische Bewegungsphasen."
  },
  "mi-squatpry": {
    "directory": "squat-pry",
    "file": "loop.gif",
    "labels": [
      "Stabile tiefe Hocke",
      "Ruhig zu einer Seite",
      "Ruhig zur anderen Seite"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Füsse stabil.",
      "Atmung ruhig.",
      "keine scharfen Gelenkgefühle."
    ],
    "description": "Deep Squat Pry: schematische Bewegungsphasen."
  },
  "mi-catcow": {
    "directory": "cat-cow",
    "file": "loop.gif",
    "labels": [
      "Rücken sanft runden",
      "Neutral durchbewegen",
      "Sanft strecken"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Langsam segmentieren.",
      "keine Endrange erzwingen.",
      "Atmung mit Bewegung."
    ],
    "description": "Segmental Cat-Cow: schematische Bewegungsphasen."
  },
  "sa-pogo": {
    "directory": "pogo",
    "file": "loop.gif",
    "labels": [
      "Kurzer Bodenkontakt",
      "Aus dem Sprunggelenk federn",
      "Leicht landen"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      700,
      800,
      800
    ],
    "cues": [
      "Kurzer Bodenkontakt.",
      "aufrecht.",
      "federnd aus dem Sprunggelenk."
    ],
    "description": "Pogo Jumps: schematische Bewegungsphasen."
  },
  "sa-explosivepullup": {
    "directory": "explosive-pullup",
    "file": "loop.gif",
    "labels": [
      "Ruhiger Hang",
      "Schnell hochziehen",
      "Kontrolliert zurück"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Schnell hoch.",
      "kontrolliert runter.",
      "kein Beinschwung."
    ],
    "description": "Explosive Pull-up: schematische Bewegungsphasen."
  },
  "sa-rotpower": {
    "directory": "cable-rotation",
    "file": "loop.gif",
    "labels": [
      "Stand und Griff vorbereiten",
      "Aus Hüfte und Rumpf drehen",
      "Endposition · Griff festhalten"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Aus der Hüfte starten.",
      "Kraft durch den Rumpf übertragen.",
      "Arm folgt nur der Rotation.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Explosive Kabelrotation: schematische Bewegungsphasen."
  },
  "sa-revlunge~reverse": {
    "directory": "reverse-lunge-db",
    "file": "loop.gif",
    "labels": [
      "Aufrechter Stand",
      "Rückschritt",
      "Kontrolliert absenken"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Vorderer Fuss voll.",
      "Becken stabil.",
      "aus Vorderbein hoch.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Reverse Lunge mit Kurzhanteln: schematische Bewegungsphasen."
  },
  "sa-revlunge~split-squat": {
    "directory": "split-squat-db",
    "file": "loop.gif",
    "labels": [
      "Fester Schrittstand",
      "Beide Knie beugen",
      "Kontrollierte Tiefe"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Vorderer Fuss voll belastet.",
      "kontrolliert tief.",
      "kein Aufprall unten.",
      "Becken stabil.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Split Squat mit Kurzhanteln: schematische Bewegungsphasen."
  },
  "sa-leraise": {
    "directory": "hanging-legraise",
    "file": "loop.gif",
    "labels": [
      "Ruhiger Hang",
      "Beine ohne Schwung anheben",
      "Becken aktiv einrollen"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Kein Kipping.",
      "Rippen/Becken kontrolliert.",
      "langsam absenken."
    ],
    "description": "Hanging Leg Raise: schematische Bewegungsphasen."
  },
  "sa-tibialis": {
    "directory": "tibialis",
    "file": "loop.gif",
    "labels": [
      "Fersen fest am Boden",
      "Vorderfüße anheben",
      "Obere Position kontrollieren"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Keine Hüftbewegung.",
      "volle Dorsalflexion.",
      "kontrollierter Rückweg."
    ],
    "description": "Tibialis Raise: schematische Bewegungsphasen."
  },
  "fr-adductor": {
    "directory": "adductor-liftoff",
    "file": "loop.gif",
    "labels": [
      "Seitlich ausgestrecktes Bein",
      "Bein aktiv leicht anheben",
      "Becken ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Becken ruhig.",
      "Bein aktiv anheben.",
      "kleine ROM ist okay.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Adductor Lift-off: schematische Bewegungsphasen."
  },
  "fr-frog": {
    "directory": "frog-hold",
    "file": "loop.gif",
    "labels": [
      "Breiter gepolsterter Kniestand",
      "Hüfte sanft zurück",
      "Ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1500,
      3500
    ],
    "cues": [
      "Becken kontrolliert.",
      "ruhig atmen.",
      "kein scharfer Leistenschmerz."
    ],
    "description": "Frog Stretch: schematische Bewegungsphasen."
  },
  "fr-middlesplit": {
    "directory": "middle-split",
    "file": "loop.gif",
    "labels": [
      "Mit Blöcken abstützen",
      "Kontrolliert weiter öffnen",
      "Ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1500,
      3500
    ],
    "cues": [
      "Füsse/Knie passend ausrichten.",
      "Stütze nutzen.",
      "kontrolliert rein und raus."
    ],
    "description": "Middle Split mit Stütze: schematische Bewegungsphasen."
  },
  "fr-laterallunge": {
    "directory": "lateral-lunge",
    "file": "loop.gif",
    "labels": [
      "Aufrechter Stand",
      "Schritt zur Seite",
      "Hüfte kontrolliert zurück"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Hüfte zur belasteten Seite.",
      "Fuss voll.",
      "kein Abprallen.",
      "Beide Seiten gemäß Trainingsvorgabe ausführen; die Abbildung zeigt eine Beispielseite."
    ],
    "description": "Lateral Lunge, langsam/tief: schematische Bewegungsphasen."
  },
  "fr-horsestance": {
    "directory": "horse-stance",
    "file": "loop.gif",
    "labels": [
      "Breiter Stand",
      "Gleichmäßig absenken",
      "Position ruhig halten"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1300,
      1500,
      3500
    ],
    "cues": [
      "Rumpf aufrecht.",
      "Knie nicht nach innen.",
      "gleichmässig belasten."
    ],
    "description": "Horse Stance: schematische Bewegungsphasen."
  },
  "mo-jump": {
    "directory": "vertical-jump",
    "file": "loop.gif",
    "labels": [
      "Sprung vorbereiten",
      "Kraftvoll abspringen",
      "Leise und stabil landen"
    ],
    "sequence": [
      0,
      1,
      2
    ],
    "durations": [
      1200,
      900,
      1600
    ],
    "cues": [
      "Die Animation zeigt die Variante Vertical Jump. Zwischen den Sprüngen vollständig stabilisieren.",
      "Maximal hoch/weit.",
      "leise, stabile Landung.",
      "Knie folgen Fussrichtung."
    ],
    "description": "Broad oder Vertical Jump: schematische Bewegungsphasen."
  },
  "mo-pullup": {
    "directory": "pullup-weighted",
    "file": "loop.gif",
    "labels": [
      "Kontrollierter Hang",
      "Ohne Schwung hochziehen",
      "Obere Position"
    ],
    "sequence": [
      0,
      1,
      2,
      1
    ],
    "durations": [
      1100,
      1100,
      1100,
      1100
    ],
    "cues": [
      "Rippen kontrolliert.",
      "Beine ruhig.",
      "Zug ohne Schwung.",
      "reproduzierbare obere Endposition."
    ],
    "description": "Weighted Pull-up, voller kontrollierter ROM: schematische Bewegungsphasen."
  },
  "sa-finisher": {
    "directory": "conditioning-example",
    "file": "loop.gif",
    "labels": [
      "Ring-Liegestütz · Phase 1",
      "Ring-Liegestütz · Phase 2",
      "Ring-Liegestütz · Phase 3",
      "Ringrudern · Phase 1",
      "Ringrudern · Phase 2",
      "Ringrudern · Phase 3",
      "Goblet Squat · Phase 1",
      "Goblet Squat · Phase 2",
      "Goblet Squat · Phase 3"
    ],
    "sequence": [
      0,
      1,
      2,
      1,
      0,
      3,
      4,
      5,
      4,
      3,
      6,
      7,
      8,
      7,
      6
    ],
    "durations": [
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000,
      1000
    ],
    "cues": [
      "Beispiel für eine Runde. Übungsauswahl und Wiederholungen richten sich nach deinem Finisher; die Übergänge sind keine durchgehende Bewegung.",
      "Zirkel aus bereits bekannten, sauberen Übungen (z.B. Ring Push-up, Ring Row, KH-Squat) im 3:1-Verhältnis - spiegelt die Runden-Struktur von Boxen/MMA. Keine neuen Technikregeln. Runde abbrechen oder Tempo/Reps reduzieren, bevor Technik deutlich zerfällt."
    ],
    "description": "Runden-Conditioning: schematische Bewegungsphasen."
  }
};
